# Generated by Django 2.2.5 on 2019-09-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProduit', models.CharField(max_length=200)),
                ('familleProduit', models.CharField(max_length=200)),
                ('descriptionProduit', models.CharField(max_length=200)),
                ('quantiteMin', models.PositiveIntegerField()),
                ('packaging', models.PositiveIntegerField()),
                ('prix', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='id_client',
            new_name='client_id',
        ),
    ]
