# Generated by Django 2.2.5 on 2019-10-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_auto_20191005_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
